fix: Add automatic release versioning

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -25,18 +25,61 @@ jobs:
           fetch-depth: 0
           token: ${{ steps.generate_token.outputs.token }}
 
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.12"
+      - name: Setup | Force release branch to be at workflow sha
+          run: |
+            git reset --hard ${{ github.sha }}
 
-      - name: Install Dependencies
+      - name: Evaluate | Verify upstream has NOT changed
+        # Last chance to abort before causing an error as another PR/push was applied to
+        # the upstream branch while this workflow was running. This is important
+        # because we are committing a version change (--commit). You may omit this step
+        # if you have 'commit: false' in your configuration.
+        #
+        # You may consider moving this to a repo script and call it from this step instead
+        # of writing it in-line.
+        shell: bash
         run: |
-          python -m pip install --upgrade pip
-          pip install python-semantic-release
+          set +o pipefail
+          
+          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
+          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
+          
+          set -o pipefail
+          
+          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
+              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
+              exit 1
+          fi
+          
+          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
+          
+          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
+              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
+              exit 1
+          fi
+          
+          HEAD_SHA="$(git rev-parse HEAD)"
+          
+          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
+              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
+              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
+              exit 1
+          fi
+          
+          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
+
+      - name: Prepare release
+        id: prepare-release
+        uses: python-semantic-release/python-semantic-release@v9.21.1
+        env:
+            GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
+        with:
+          github_token: ${{ steps.generate_token.outputs.token }}
 
       - name: Release to GitHub
+        uses: python-semantic-release/publish-action@v9.21.1
         env:
           GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-        run: |
-          semantic-release publish
+        with:
+          github_token: ${{ steps.generate_token.outputs.token }}
+          tag: ${{ steps.prepare-release.outputs.tag }}
